/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsIdRouteImport } from './routes/chats/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instructions': typeof InstructionsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instructions': typeof InstructionsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instructions': typeof InstructionsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/chats/$id': typeof ChatsIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instructions'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/chats/$id'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instructions'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/chats/$id'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/instructions'
    | '/memory'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/chats/$id'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstructionsRoute: typeof InstructionsRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
  ChatsIdRoute: typeof ChatsIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstructionsRoute: InstructionsRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
  ChatsIdRoute: ChatsIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
